site_name: GOGNAUTS
nav:
    - Home: index.md
    - Halo: halo.md
    - IRC: irc.html
    - Alternatives: alternatives.md
    - Gognauts: gognauts.md
    - Blood Realm: bloodrealm.md
    - Architecture: architecture.md
    - Darkness: darkness.md
theme: readthedocs
