site_name: GOGHAND
nav:
    - Home: index.md
    - About: about.md
    - French: french.md
    - Learn Docs: learndocs.md
    - 'Trinity Of Terror':
        - 'Goghand': './chars/goghand.md':
theme: readthedocs
