site_name: GOGNAUTS
nav:
    - Home: index.md
    - Games: games.md
    - IRC: irc.html
    - Link City: linkcity.md    
    - Alternatives: alternatives.md
    - RSS: rss.md
    - Tumblr Tools: tumblr.md    
    - Radio broadcasts: radio.md
    - Interesting concepts: intconcepts.md    
    - Book Info: bookinfo.md
    - Dance n Music: dusic.md    
    - Comics: comics.md
    - Archit. n Geology: archgeo.md
    - Linguistics: ling.md    
    - Darkness: darkness.md
    - Gognauts: gognauts.md    
theme: readthedocs