site_name: GOGNAUTS
nav:
    - Home: index.md
    - Trinity Of Terror: ./tot/
    - Gognauts: gognauts.md
    - Alternatives: alternatives.md
    - Blood Realm: bloodrealm.md
    - Darkness: darkness.md
    - IRC: irc.html
theme: readthedocs
