site_name: GOGNAUTS
nav:
    - Home: index.md
    - Halo/Elite Dangerous: halo.md
    - IRC: irc.html
    - Alternatives: alternatives.md
    - RSS It will change your life: rss.md
    - Radio broadcasts: radio.md    
    - Gognauts: gognauts.md
    - Blood Realm: bloodrealm.md
    - Architecture: architecture.md
    - Darkness: darkness.md
theme: readthedocs
