site_name: GOGHAND
nav:
    - Home: index.md
    - About: about.md
    - French: french.md
    - Learn Docs: learndocs.md
    - Goghand: ./chars/goghand.md
       - 'User Guide':
        - 'Writing your docs': 'writing-your-docs.md'
theme: readthedocs
